### ISSUE TITLE
after_epoch_profile gets invalid streams

### ISSUE THREAD

**Issue by FloopCZ** [iterait/emloop#40]
`after_epoch_profile` hook call is given invalid streams for `emloop eval`. E.g., for `emloop eval valid`, it actually gets `streams=['train']`.

This is the line to blame: https://github.com/iterait/emloop/blob/dev/emloop/main_loop.py#L261
It should use the function argument `streams` instead of `[self._train_stream_name] + self._extra_streams`.

Regression test is necessary when submitting a pull request.

@bedapisl, have you already looked into it? Maybe @gdynusa would be interested if not.

**Comment by bedapisl** [comment]
Yes, but I forget to commit it, sorry.
