### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by bedapisl** [iterait/emloop#65]
Training with emloop causes memory leaks. I think the problem is Python buffering, because with `main_loop.buffer: 0` no leaks happened to me. I tried iterating through different streams and the leaks happens only for some of them so I think there may be a race condition.

Here is script which produces the leak:
 ```
from emloop.api import create_dataset, load_yaml
from emloop.datasets.stream_wrapper import StreamWrapper
import time

config = load_yaml("models/detection.yaml")
dataset = create_dataset(config)

dataset._initialize_cpp_dataset()

stream = StreamWrapper(dataset.valid_stream, buffer_size=4)

with stream:
    for epoch in range(100):
        for batch in stream:
            with stream.allow_buffering:
                time.sleep(0.0)

        print(f"Epoch {epoch} done")
```
It allocates extra ~250MB every ~100 seconds. You need `faces` repository to run it, although (according to Filip) the leak also happened with Isletnet streams.

**Comment by bedapisl** [comment]
I think the memory leak also happened with buffer=0.

**Comment by blazekadam** [comment]
Can you come up with even more trivial minimal (not) working example (i.e., without our cpp dataset)?

**Comment by bedapisl** [comment]
I tried but I wasn't successful so I gave up after one day. But if this has priority, I can focus on it.

**Comment by FloopCZ** [comment]
This was probably caused by a bug in the project itself, not emloop. Feel free to reopen if the issue persists.
